### Register Citizen
POST http://localhost:9090/api/citizen/register
Content-Type: application/json

{
  "name": "John",
  "email": "gmail.com",
  "password": "1234",
  "phoneNumber": 1234567
}

###

### Login Citizen
POST http://localhost:9090/api/citizen/login
Content-Type: application/json

{
    "email": "gmail.com",
    "password": "1234"
}

###

### Access Citizen Dashboard (Authenticated)
GET http://localhost:9090/api/home
Cookie: auth_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc0NjUxNjI1NSwiZXhwIjoxNzQ2NTUyMjU1fQ.MyXpMLI_R_7dPvyWUjmTICcWVkXd7EhFcOqkXrN5qxA




### Register Law Enforcement
POST http://localhost:9090/api/lawEnforcement/register
Content-Type: application/json

{
  "policeStationName": "2",
  "policeStationEmail": "2",
  "policeStationContactNo": 2,
  "sho": "2",
  "address": "2",
  "password": "2"
}

###

### Login Law Enforcement
POST http://localhost:9090/api/lawEnforcement/login
Content-Type: application/json

{
    "email": "1",
    "password": "1"
}

###

### Access Law Enforcement Dashboard (Authenticated)
GET http://localhost:9090/api/test
Cookie: auth_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNzQ2NTIxNjE0LCJleHAiOjE3NDY1NTc2MTR9.KQd91FrfZqCqe5Z-_NMe40M-y0w8t1d6ytokuyOuMpk


### Create Complaint
POST http://localhost:9090/api/complaints
Content-Type: application/json
Cookie: auth_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnbWFpbC5jb20iLCJpYXQiOjE3NDc0MTY0MzksImV4cCI6MTc0NzQ1MjQzOX0.YLVwdtiAryei-anIMpJ58lhZvWJrw2m6IIVoVUF3XWg

{
    "title": "Theft Incident",
    "description": "A theft occurred at my residence.",
    "supportingDocument": "theft_report.pdf",
    "incidentLocationLat": 28.7041,
    "incidentLocationLong": 77.1025,
    "status": "Pending",
    "witnessId": 1,
    "assignedToId": 1
}

### Find All Complaints

GET http://localhost:9090/api/complaints/all
Cookie: auth_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzQ3NTg4NTExLCJleHAiOjE3NDc2MjQ1MTF9.MNgyqFu3OUmC5Z3ZD9nu8dQVz7opIJm8H7kq7sh710U